version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      PORT: 80
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
